# Generated by Django 4.2.13 on 2024-06-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
    ]
